# a cluster with a control-plane nodes and 2 workers nodes
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: hiredscore
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30007
        hostPort: 30007
        listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp
  - role: worker
  - role: worker
