apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-ha
  labels:
    app: pizza
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: pizza
          image: shay79il/pizza-site:1.0.0
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pizza-ha-svc
spec:
  type: NodePort
  selector:
    app: pizza
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
